### ISSUE TITLE
Test responsiveness on various screen sizes

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/docs-theme#52]
Make sure that the site looks good on screen sizes ranging from phones to large monitors.

**Comment by daremiyo** [comment]
- Card style documentation item display squashed on phone screen 
- Table of contents squashed on phone screen
- The white space on the right margin doesn't adjust to phone screen

**Comment by kemartin2015** [comment]
These problems are not as pronounced on iPad screens, but some of the longer titles in the table of contents result in orphan letters.
