### ISSUE TITLE
Flesh out readme

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/docs-theme#57]
Hey, this Readme is a little sparse. Might want to flesh it out with some information about what it's built in, what it's for, etc.

**Comment by helrond** [comment]
@HaSistrunk see [this repo](https://github.com/RockefellerArchiveCenter/templates) for some helpful license and readme templates

**Comment by daremiyo** [comment]
@helrond @HaSistrunk @kemartin2015 hi everyone, so I opened a branch with an initial draft of the readme. I would really appreciate feedback to see if I'm going in the right direction. thanks!

**Comment by helrond** [comment]
This looks great @daremiyo! I think it's pretty complete. The only thing I'd ask is to format the block quotes so they're code blocks either by wrapping them in \` or indenting. You can use the handy Preview in GitHub to make sure it looks right.

**Comment by daremiyo** [comment]
@helrond great! I just fixed those quotes, so I'll open up a pull request
